org: mikebasdeo
app: helloworld
service: serverless

provider:
  name: aws
  runtime: nodejs12.x
  # profile: femasters
  region: us-west-1
  stage: dev

functions:
  helloworld:
    handler: src/helloworld.handler

plugins:
  - serverless-offline

    
